ignore = [
    "D203",  # ignores D203 (one-blank-line-before-class) since we use D211 (no-blank-line-before-class)
    "D213",  # ignores D213 (multi-line-summary-second-line) since we use D212 (multi-line-summary-first-line)
]

line-length = 120

select = [
    "ALL",  # enable all rules by default
]

# Allow imports relative to these directories.
src = ["src"]


[flake8-annotations]

# Whether to suppress ANN401 for dynamically typed *args and **kwargs arguments
allow-star-arg-any = true


[flake8-type-checking]

# Exempt certain modules from needing to be moved into type-checking blocks.
exempt-modules = []

# Enforce TC001, TC002, and TC003 rules even when valid runtime imports are present for the same module.
strict = true


[isort]

# A list of modules to consider first-party, regardless of whether they
# can be identified as such via introspection of the local filesystem.
known-first-party = ["src"]

# The number of blank lines to place after imports.
lines-after-imports = 2

# Order imports by type, which is determined by case, in addition to alphabetically.
order-by-type = false

# Add the specified import line to all files.
required-imports = ["from __future__ import annotations"]
