[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
authors = ["Eugene <eugeneturkin@gmail.com>"]
description = "Backend for artist-centered image hosting."
name = "acih-backend"
readme = "README.md"
version = "0.1.0"


[tool.poetry.dependencies]
python = "3.11.*"
