name: acih-ci-lint

services:
  app-build: &app-build
    build:
      context: ../../..  # path from the current file to the project root dir
      dockerfile: envs/ci/lint/Dockerfile  # path from the project root dir to the Dockerfile
      cache_from:
        - type=local,src=${BUILDX_CACHE_SRC}
      cache_to:
        - type=local,dest=${BUILDX_CACHE_DEST}

  mypy:
    <<: *app-build
    volumes:
      - ~/.mypy_cache:/app/.mypy_cache
    entrypoint: mypy

  ruff:
    <<: *app-build
    volumes:
    - ~/.ruff_cache:/app/.ruff_cache
    entrypoint: ruff check src tests

  flake8:
    <<: *app-build
    entrypoint: flake8

  pylint:
    <<: *app-build
    entrypoint: pylint src tests --jobs=0

  poetry-lock-check:
    <<: *app-build
    entrypoint: poetry lock --check
