name: acih-local-dev

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env  # path to .env file relative to the current file directory
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-12-06T09-09-22Z
    ports:
    - "9000:9000"
    - "9090:9090"
    env_file:
      - .env
    volumes:
      - minio:/data
    command: ["server", "/data", "--console-address", ":9090"]

volumes:
  postgres:
  minio:
