"""add timestamps to account, profile, session, following, post  models

Revision ID: f96276677b9d
Revises: 12096e20d6be
Create Date: 2024-05-31 17:02:45.107266+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96276677b9d'
down_revision: Union[str, None] = '12096e20d6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('following', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('post', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('profile', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('session', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'created_at')
    op.drop_column('profile', 'created_at')
    op.drop_column('post', 'created_at')
    op.drop_column('following', 'created_at')
    op.drop_column('account', 'created_at')
    # ### end Alembic commands ###
