"""create account profile password hash tables

Revision ID: be560fc34518
Revises: 18d944595504
Create Date: 2024-01-27 12:39:56.348778+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be560fc34518'
down_revision: Union[str, None] = '18d944595504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_hash',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('SHA256', name='algorithm_enum'), nullable=False),
    sa.Column('salt', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('profile',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('avatar_id'),
    sa.UniqueConstraint('background_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('password_hash')
    op.drop_table('account')
    sa.Enum(name='algorithm_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
