"""create following table

Revision ID: fb0a6d39cb9a
Revises: fc81b2fd94cf
Create Date: 2024-02-29 10:49:49.640740+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0a6d39cb9a'
down_revision: Union[str, None] = 'fc81b2fd94cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('follower_id != followee_id', name='check_following_self'),
    sa.ForeignKeyConstraint(['followee_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='unique_following')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    # ### end Alembic commands ###
