"""create file table

Revision ID: 432b2b7bb5ae
Revises: be560fc34518
Create Date: 2024-02-05 14:03:16.967950+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432b2b7bb5ae'
down_revision: Union[str, None] = 'be560fc34518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extension', sa.Enum('JPE', 'JPEG', 'JPG', 'PNG', name='extension_enum'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.Enum('IMAGE_PNG', 'IMAGE_JPEG', name='mimetype_enum'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('upload_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    sa.Enum(name='extension_enum').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='mimetype_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
