"""add foreign key to profile columns

Revision ID: fc81b2fd94cf
Revises: 3229a38f7b40
Create Date: 2024-02-26 16:34:40.525449+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc81b2fd94cf'
down_revision: Union[str, None] = '3229a38f7b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("profile__background_id__fk", 'profile', 'file', ['background_id'], ['id'])
    op.create_foreign_key("profile__avatar_id__fk", 'profile', 'file', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile__background_id__fk", 'profile', type_='foreignkey')
    op.drop_constraint("profile__avatar_id__fk", 'profile', type_='foreignkey')
    # ### end Alembic commands ###
