name: Cleanup
run-name: Cleanup for branch "${{ github.ref_name }}"

on: [delete, push]
jobs:
  on-delete:
    name: On delete
    if: github.event.ref_type == 'branch' && github.event_name == 'delete'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ./envs/ci/cleanup/requirements.txt

      - name: Run script
        env:
          DELETED_BRANCH_NAME: ${{ github.event.ref }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 ./envs/ci/cleanup/branch_on_delete.py

  on-push:
    name: On push
    if: github.ref_type == 'branch' && github.event_name == 'push' && github.event.forced
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ./envs/ci/cleanup/requirements.txt

      - name: Run script
        env:
          REBASED_BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 ./envs/ci/cleanup/branch_on_forcepush.py
