name: Cleanup
run-name: Cleanup for branch "${{ github.event.ref }}"

on: delete
jobs:
  on-delete:
    name: On delete
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ./envs/ci/cleanup/requirements.txt

      - name: Run script
        env:
          DELETED_BRANCH_NAME: ${{ github.event.ref }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 ./envs/ci/cleanup/branch_on_delete.py
