name: Test
run-name: Test commit "${{ github.sha }}"

on: push
jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        env:
          CACHE_KEY_PREFIX: 'envs-ci-test'  # prefix should match directory which contains Dockerfile used for build
        uses: ./.github/actions/docker/use-buildx-cache

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: ~/.pytest_cache
          key: pytest-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            pytest-${{ runner.os }}-${{ github.ref_name }}
            pytest-${{ runner.os }}-${{ github.event.repository.default_branch }}

      - name: Create .env file
        run: cp envs/ci/test/example.env envs/ci/test/.env

      - name: Build Pytest & services
        run: docker compose --file envs/ci/test/docker-compose.yml build

      - name: Run Pytest & services
        run: |
          docker compose --file envs/ci/test/docker-compose.yml up --quiet-pull --attach=pytest --exit-code-from=pytest

      - name: Update buildx cache
        env:
          ENV_FILE: envs/ci/test/.env
        uses: ./.github/actions/docker/update-buildx-cache
